# Generated by Django 6.0.5 on 2026-05-10 07:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kwh', models.DecimalField(decimal_places=6, max_digits=10)),
                ('supply_kwh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('demand_kwh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supply_demand_ratio', models.DecimalField(decimal_places=4, max_digits=6)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.PositiveIntegerField()),
                ('supply', models.PositiveIntegerField()),
                ('demand', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_weight', models.DecimalField(decimal_places=2, default=0.6, max_digits=4)),
                ('demand_weight', models.DecimalField(decimal_places=2, default=0.4, max_digits=4)),
                ('min_price_floor', models.DecimalField(decimal_places=6, default=0.07, max_digits=10)),
                ('max_price_ceiling', models.DecimalField(decimal_places=6, default=0.12, max_digits=10)),
                ('update_frequency_secs', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('consumer', 'Consumer'), ('producer', 'Producer'), ('both', 'Both'), ('admin', 'Admin')], default='consumer', max_length=20)),
                ('wallet_address', models.CharField(blank=True, max_length=42, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoTradeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price_per_kwh', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('max_kwh_per_trade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_price_per_kwh', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('sell_when_battery_pct', models.PositiveIntegerField(blank=True, null=True)),
                ('active_start_time', models.TimeField(blank=True, null=True)),
                ('active_end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('maintenance', 'Maintenance')], default='info', max_length=20)),
                ('recipients', models.CharField(choices=[('all', 'All Users'), ('consumers', 'Consumers Only'), ('producers', 'Producers Only')], default='all', max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_earned', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_withdrawn', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('solar', 'Solar Panel'), ('wind', 'Wind Turbine'), ('battery', 'Battery Storage')], max_length=20)),
                ('capacity_kw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_output', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('charging', 'Charging'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('smart_meter_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.PositiveIntegerField(unique=True)),
                ('energy_amount', models.PositiveBigIntegerField()),
                ('base_price_per_unit', models.CharField(max_length=78)),
                ('price_per_unit', models.CharField(max_length=78)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed'), ('dynamic', 'Dynamic')], default='dynamic', max_length=10)),
                ('min_price_per_unit', models.CharField(blank=True, max_length=78, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='active', max_length=20)),
                ('device_type', models.CharField(default='solar', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='api.energydevice')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price_per_unit', models.CharField(max_length=78)),
                ('energy_amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered')], default='pending', max_length=20)),
                ('counter_price', models.CharField(blank=True, max_length=78, null=True)),
                ('on_chain_bid_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.energylisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_above', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('alert_below', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_address', models.CharField(max_length=42)),
                ('seller_address', models.CharField(max_length=42)),
                ('energy_amount', models.PositiveBigIntegerField()),
                ('total_cost', models.CharField(max_length=78)),
                ('multiplier_used', models.PositiveIntegerField(default=100)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='api.bid')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.energylisting')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('safe', 'Safe'), ('confirmed', 'Confirmed Fraud')], default='open', max_length=20)),
                ('flagged_by', models.CharField(default='system', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reviews', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to='api.transaction')),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', 'Earn'), ('spend', 'Spend'), ('withdraw', 'Withdraw'), ('topup', 'Top Up'), ('reward', 'Reward')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=6, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='api.creditwallet')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_records', to='api.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
