# Generated by Django 6.0.5 on 2026-05-16 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energylisting',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='energylisting',
            name='is_admin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='energylisting',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='energylisting',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='energylisting',
            name='price_type',
            field=models.CharField(default='dynamic', max_length=10),
        ),
        migrations.AlterField(
            model_name='energylisting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
